### ISSUE TITLE
issue writing example

### ISSUE THREAD

**Issue by wibeasley** [wibeasley/shiny-class-2015#6]
- Plain words.  Nothing special.
- Here's the most recent version of the code: https://github.com/wibeasley/shiny-class-2015/blob/master/Thomas/lesson_2/ui.R
- A moment in time: https://github.com/wibeasley/shiny-class-2015/blob/7392de6225e23d100715a3e0c0141aa030e53c58/Thomas/lesson_2/ui.R
- Specific line: https://github.com/wibeasley/shiny-class-2015/blob/7392de6225e23d100715a3e0c0141aa030e53c58/Thomas/lesson_2/ui.R#L15
- Block: https://github.com/wibeasley/shiny-class-2015/blob/7392de6225e23d100715a3e0c0141aa030e53c58/Thomas/lesson_2/ui.R#L15-L18

**Comment by wibeasley** [comment]
- Refer to inside issue:  #2; refer to external issue: https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/issues/3; another inside issue: https://github.com/wibeasley/shiny-class-2015/issues/4

**Comment by wibeasley** [comment]
I've done my part now.  @thomasnwilson, please take over.

**Comment by wibeasley** [comment]
@dwellsokc, now it's your turn.

**Comment by wibeasley** [comment]
- Pretty link to [current file](https://github.com/wibeasley/shiny-class-2015/blob/master/Thomas/lesson_2/ui.R).  bgvb
- The gender variable is male.
- The gender variable is `male`.
- Here's a block of R code:

``` r
library(shiny)
library(ggplot2)

# Define server logic required to draw a histogram
shinyServer(function(input, output) {
})
```
- Here's a block of SQL code:

``` sql
SELECT * FROM tblParticipant;
```

**Comment by wibeasley** [comment]
- @sbohora, I fixed my mistake.  I [left out a quote](https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/commit/38c1bb87593e4f39ea24ca3bfce52eb90a12f348)
- Here are two more things we need to do.
- [x] sign paper
- [x] mail paper

**Comment by geauxdojang** [comment]
@wibeasley : Keys to ExamplesAndPatterns #7
