### ISSUE TITLE
Keys to ExamplesAndPatterns

### ISSUE THREAD

**Issue by geauxdojang** [wibeasley/shiny-class-2015#7]
This is a key to https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/issues/3

**Comment by geauxdojang** [comment]
Item 1:  link to R script 
https://github.com/wibeasley/shiny-class-2015/blob/master/Som/RFileForGithubExamplesPractice/practice.R

Item 2: Link to a snapshot
https://github.com/wibeasley/shiny-class-2015/blob/3965e8a3b9cd6f075ec9efad0eebf04803531886/Som/RFileForGithubExamplesPractice/practice.R

Item 3: 8th line is selcted
https://github.com/wibeasley/shiny-class-2015/blob/master/Som/RFileForGithubExamplesPractice/practice.R#L8

Item 4: Select block of code
https://github.com/wibeasley/shiny-class-2015/blob/master/Som/RFileForGithubExamplesPractice/practice.R#L8-L12

Item 5 and 6: @sbohora: Please refer to issue #6 

Item 7: 
Here is a [link](https://github.com/wibeasley/shiny-class-2015/issues/6) to an issue you may want to look at

Item 8: Inline code
Date of birth is `ds$DOB`

Item 9: Block of code

``` r
mat <- NULL
for (i in 1:3){
  for (j in 1:4){
    cbinding <- cbind(i,j)
    mat <- rbind(mat, cbinding)
  }
}
```

Item 10: Changes/commits
Here are the changes: https://github.com/wibeasley/shiny-class-2015/commit/53d1895a7ecef2ff415ac70b216e7c7ddb97eafd

Item 11: Here is a list of tasks
- [ ] Read the first post
- [ ] Read the "Comments"
- [ ] Read more about [GFM](https://help.github.com/articles/github-flavored-markdown)

**Comment by wibeasley** [comment]
great job, @sbohora

**Comment by sbohora** [comment]
https://github.com/wibeasley/shiny-class-2015/blob/master/Som/RFileForGithubExamplesPractice/practice.R

@wibeasley : We are now working excercise.
